import { Inject, Injectable } from '@nestjs/common';
import {
  PAYSLIP_STATUS,
  payslipPeriodLabel,
  STATUS_META,
  type RecordStatus,
} from '@nbr/shared';
import {
  drawNotice,
  drawParties,
  drawTable,
  drawTotals,
  formatDate,
  INK,
  keyValues,
  renderDocument,
  sectionTitle,
  type TotalLine,
} from './pdf-kit';

import { and, desc, eq, isNull } from 'drizzle-orm';
import { ENV } from '../config/config.module';
import type { Env } from '../config/env';
import { NotFoundError, ValidationError } from '../common/errors';
import type { Database } from '../database/client';
import { DB } from '../database/database.tokens';
import * as schema from '../database/schema';
import { StorageService } from '../storage/storage.service';



export interface GeneratedDocument {
  readonly url: string;
  readonly fileName: string;
  /**
   * Always `application/pdf`, and returned so a generated document answers the
   * same shape as a stored one.
   *
   * That sameness is the point: `FilePreviewSheet` renders evidence, applicant
   * attachments and onboarding files from `{ url, fileName, contentType }`, and
   * matching it means an invoice previews through the component that already
   * works rather than through a second one built to look like it.
   */
  readonly contentType: string;
}

/**
 * How the signed URL should behave in a browser.
 *
 * `inline` renders the PDF in place — which is what "preview the invoice before
 * sharing it" means — and `attachment` saves it.
 */
export type DocumentDisposition = 'attachment' | 'inline';


/**
 * On-demand PDFs: the applicant file, the selection letter and the invoice.
 *
 * Generated per request rather than stored against the record. All three
 * describe the record *as it currently stands*, and a copy written to the vault
 * six weeks ago would show a superseded package price or a former assignee —
 * worse than no copy, because it looks authoritative.
 *
 * The generated bytes are written to storage only so the browser can be handed
 * a short-lived signed URL; the API never streams a file through an app worker
 * (§7). Those objects are disposable — losing one costs a regeneration.
 */
@Injectable()
export class DocumentsService {
  constructor(
    @Inject(DB) private readonly db: Database,
    @Inject(ENV) private readonly env: Env,
    private readonly storage: StorageService,
  ) {}

  // ── Applicant file (§4 Quick Actions, §11.9) ──────────────────────────────

  async applicantFile(
    applicantId: string,
    disposition: DocumentDisposition = 'attachment',
  ): Promise<GeneratedDocument> {
    const [applicant] = await this.db
      .select()
      .from(schema.applicants)
      .where(and(eq(schema.applicants.id, applicantId), isNull(schema.applicants.deletedAt)))
      .limit(1);

    if (!applicant) throw new NotFoundError('Applicant');

    const records = await this.db
      .select({
        recordCode: schema.records.recordCode,
        status: schema.records.status,
        applicationDate: schema.records.applicationDate,
        paymentStatus: schema.records.paymentStatus,
        deliveryStatus: schema.records.deliveryStatus,
        recordTitle: schema.achievements.recordTitle,
      })
      .from(schema.records)
      .leftJoin(schema.achievements, eq(schema.achievements.recordId, schema.records.id))
      .where(and(eq(schema.records.applicantId, applicantId), isNull(schema.records.deletedAt)))
      .orderBy(desc(schema.records.applicationDate));

    const pdf = await renderDocument(
      {
        organisation: this.env.DPDP_DATA_FIDUCIARY_NAME,
        title: 'Applicant file',
        reference: applicant.applicantCode,
        issuedOn: new Date(),
      },
      `Applicant file · ${applicant.applicantCode}`,
      (doc) => {
        sectionTitle(doc, 'Applicant');
        keyValues(
          doc,
          [
            ['Name', applicant.fullName],
            ['Applicant ID', applicant.applicantCode],
            ['Mobile', applicant.mobile],
            ['Email', applicant.email],
            ['Date of birth', formatDate(applicant.dateOfBirth)],
            ['Country', applicant.country ?? 'India'],
            [
              'Address',
              [applicant.addressLine, applicant.city, applicant.state, applicant.pincode]
                .filter(Boolean)
                .join(', ') || '—',
            ],
          ],
          { columns: 2, labelWidth: 92 },
        );

        sectionTitle(doc, `Records (${records.length})`);

        if (records.length === 0) {
          doc.font('Helvetica').fontSize(9).fillColor(INK.muted).text('No records on this profile.');
        } else {
          drawTable(
            doc,
            [
              { key: 'code', label: 'Record', weight: 1.1 },
              { key: 'title', label: 'Achievement', weight: 2.4 },
              { key: 'status', label: 'Status', weight: 1.2 },
              { key: 'payment', label: 'Payment', weight: 1 },
              { key: 'applied', label: 'Applied', weight: 1, align: 'right' },
            ],
            records.map((record) => ({
              code: record.recordCode,
              title: record.recordTitle ?? 'Untitled',
              status: STATUS_META[record.status as RecordStatus]?.label ?? record.status,
              payment: record.paymentStatus.replace(/_/g, ' '),
              applied: formatDate(record.applicationDate),
            })),
          );
        }

        // Identity numbers are deliberately absent: they are encrypted, access is
        // logged per read under DPDP §8(4), and a PDF is exactly the artefact
        // that escapes that control by being emailed onward.
        drawNotice(
          doc,
          'Identity document numbers are omitted from this file. They are held encrypted and released only through an audited reveal, and a PDF cannot carry that control with it.',
        );
      },
    );

    return this.publish(pdf, 'applicant', applicantId, `${applicant.applicantCode}-file.pdf`, disposition);
  }

  // ── Selection letter (§11.4) ──────────────────────────────────────────────

  async selectionLetter(
    recordId: string,
    disposition: DocumentDisposition = 'attachment',
  ): Promise<GeneratedDocument> {
    const record = await this.loadRecord(recordId);

    // A letter announcing selection for a record that was not selected would be
    // a document NBR has to stand behind. Refused rather than generated.
    const eligible: readonly string[] = [
      'selected',
      'payment_pending',
      'payment_received',
      'certificate_pending',
      'certificate_uploaded',
      'publication',
      'dispatch_pending',
      'dispatched',
      'delivered',
      'completed',
    ];
    if (!eligible.includes(record.status)) {
      throw new ValidationError({
        status: [
          `This record is at ${STATUS_META[record.status as RecordStatus]?.label ?? record.status}. A selection letter can only be issued once it has been selected.`,
        ],
      });
    }

    const pdf = await renderDocument(
      {
        organisation: this.env.DPDP_DATA_FIDUCIARY_NAME,
        title: 'Letter of selection',
        reference: record.recordCode,
        issuedOn: new Date(),
      },
      `Letter of selection · ${record.recordCode}`,
      (doc) => {
        // A letter is prose, not a form: wider leading and a real signature
        // block, because this is the one document here an applicant may print
        // and show to somebody.
        doc.moveDown(0.6);
        doc.font('Helvetica-Bold').fontSize(11).fillColor(INK.strong).text(record.applicantName);
        doc.font('Helvetica').fontSize(9).fillColor(INK.muted).text(record.applicantCode);
        doc.moveDown(1.4);

        doc
          .font('Helvetica')
          .fontSize(10.5)
          .fillColor(INK.body)
          .text(`Dear ${record.applicantName},`, { lineGap: 3 });
        doc.moveDown(0.8);

        doc.text(
          `We are pleased to confirm that your achievement, "${record.recordTitle}", has been reviewed by our verification team and selected for entry into the ${this.env.DPDP_DATA_FIDUCIARY_NAME}.`,
          { align: 'justify', lineGap: 3 },
        );
        doc.moveDown(0.7);
        doc.text(`Your record has been assigned the reference ${record.recordCode}.`, {
          align: 'justify',
          lineGap: 3,
        });
        doc.moveDown(0.7);
        doc.text(
          'Please quote this reference in any correspondence. Our team will be in touch with the next steps.',
          { align: 'justify', lineGap: 3 },
        );

        doc.moveDown(2.4);
        doc.font('Helvetica').fontSize(10).fillColor(INK.body).text('Yours sincerely,');
        doc.moveDown(2);
        doc.font('Helvetica-Bold').fontSize(10).fillColor(INK.strong).text(this.env.DPDP_DATA_FIDUCIARY_NAME);
        doc.font('Helvetica').fontSize(8.5).fillColor(INK.muted).text('Verification team');
      },
    );

    return this.publish(pdf, 'record', recordId, `${record.recordCode}-selection-letter.pdf`, disposition);
  }

  // ── Invoice (§9, §11.6) ───────────────────────────────────────────────────

  async invoice(
    recordId: string,
    disposition: DocumentDisposition = 'attachment',
  ): Promise<GeneratedDocument> {
    const record = await this.loadRecord(recordId);

    const [payment] = await this.db
      .select()
      .from(schema.payments)
      .where(eq(schema.payments.recordId, recordId))
      .limit(1);

    if (!payment) {
      throw new ValidationError({
        payment: ['No payment has been raised for this record yet.'],
      });
    }

    const [invoice] = await this.db
      .select()
      .from(schema.invoices)
      .where(eq(schema.invoices.paymentId, payment.id))
      .orderBy(desc(schema.invoices.issuedOn))
      .limit(1);

    if (!invoice) {
      throw new ValidationError({
        invoice: ['Generate the invoice number first — the figures are frozen at that point.'],
      });
    }

    const transactions = await this.db
      .select()
      .from(schema.paymentTransactions)
      .where(eq(schema.paymentTransactions.paymentId, payment.id))
      .orderBy(schema.paymentTransactions.paidOn);

    const settled = Number(payment.amountPaid) >= Number(invoice.finalAmount);

    const pdf = await renderDocument(
      {
        organisation: this.env.DPDP_DATA_FIDUCIARY_NAME,
        title: 'Tax invoice',
        reference: invoice.invoiceNumber,
        issuedOn: invoice.issuedOn ?? new Date(),
        status: invoice.cancelledAt
          ? { label: 'Cancelled', tone: 'danger' }
          : settled
            ? { label: 'Paid', tone: 'ok' }
            : { label: 'Due', tone: 'neutral' },
      },
      `Tax invoice · ${invoice.invoiceNumber}`,
      (doc) => {
        drawParties(
          doc,
          {
            heading: 'From',
            lines: [this.env.DPDP_DATA_FIDUCIARY_NAME, 'India'],
          },
          {
            heading: 'Billed to',
            lines: [record.applicantName, record.applicantCode],
          },
        );

        sectionTitle(doc, 'Details');
        keyValues(
          doc,
          [
            ['Record', `${record.recordCode} — ${record.recordTitle}`],
            ['Financial year', invoice.financialYear],
          ],
          { labelWidth: 100 },
        );

        doc.moveDown(0.6);

        /**
         * One line per charge, then the totals — never both.
         *
         * Every figure below comes off the invoice row rather than the payment
         * plan: the invoice froze them at issue, and a later price change must
         * not retroactively alter a document already sent to an applicant.
         */
        drawTable(
          doc,
          [
            { key: 'description', label: 'Description', weight: 3.4 },
            { key: 'amount', label: 'Amount', weight: 1.1, money: true },
          ],
          [{ description: payment.packageName, amount: invoice.amount }],
          { zebra: false },
        );

        const totals: TotalLine[] = [];
        if (Number(invoice.discount) > 0) {
          totals.push({ label: 'Discount', amount: invoice.discount, negative: true });
        }
        totals.push({ label: `GST (${payment.gstPercent}%)`, amount: invoice.gstAmount });
        totals.push({ label: 'Total payable', amount: invoice.finalAmount, emphasis: true });
        totals.push({ label: 'Received to date', amount: payment.amountPaid });

        const balance = Number(invoice.finalAmount) - Number(payment.amountPaid);
        // A balance line on a fully settled invoice is noise; on an outstanding
        // one it is the single most important number on the page.
        if (balance > 0) totals.push({ label: 'Balance due', amount: balance, emphasis: true });

        drawTotals(doc, totals);

        if (transactions.length > 0) {
          sectionTitle(doc, 'Payments received');
          drawTable(
            doc,
            [
              { key: 'paidOn', label: 'Date', weight: 1 },
              { key: 'mode', label: 'Mode', weight: 1.2 },
              { key: 'reference', label: 'Reference', weight: 1.8 },
              { key: 'amount', label: 'Amount', weight: 1.1, money: true },
            ],
            transactions.map((transaction) => ({
              paidOn: formatDate(transaction.paidOn),
              mode: transaction.mode.replace(/_/g, ' '),
              reference: transaction.transactionRef ?? '—',
              amount: transaction.isReversal ? `-${transaction.amount}` : transaction.amount,
            })),
          );
        }

        if (invoice.cancelledAt) {
          drawNotice(
            doc,
            `This invoice was cancelled on ${formatDate(invoice.cancelledAt)}. Reason: ${invoice.cancelReason ?? 'not recorded'}. It is retained for the audit trail and must not be treated as a demand for payment.`,
            'danger',
          );
        }
      },
    );

    return this.publish(
      pdf,
      'invoice',
      recordId,
      `${invoice.invoiceNumber.replace(/\//g, '-')}.pdf`,
      disposition,
    );
  }

  // ── Payslip (§HR) ─────────────────────────────────────────────────────────

  /**
   * The monthly payslip.
   *
   * Built through the same `renderDocument` kit as the invoice, the selection
   * letter and the applicant file, so it carries the identical masthead,
   * section rules, table styling and totals block. That sameness is the point:
   * an employee and an applicant both receive NBR paper, and a payslip that
   * looked like a different organisation's would undermine both.
   *
   * Every figure is read off the payslip row, never recomputed. The row froze
   * the salary and the day counts at generation, so this reprints exactly what
   * was issued however long ago — which is what a payslip is for.
   */
  async payslip(
    payslipId: string,
    disposition: DocumentDisposition = 'attachment',
  ): Promise<GeneratedDocument> {
    const [payslip] = await this.db
      .select()
      .from(schema.employeePayslips)
      .where(eq(schema.employeePayslips.id, payslipId))
      .limit(1);

    if (!payslip) throw new NotFoundError('Payslip');

    const [employee] = await this.db
      .select()
      .from(schema.employees)
      .where(eq(schema.employees.id, payslip.employeeId))
      .limit(1);

    if (!employee) throw new NotFoundError('Employee');

    const period = payslipPeriodLabel(payslip.periodMonth, payslip.periodYear);
    const cancelled = payslip.status === PAYSLIP_STATUS.CANCELLED;

    const pdf = await renderDocument(
      {
        organisation: this.env.DPDP_DATA_FIDUCIARY_NAME,
        title: 'Payslip',
        reference: payslip.payslipNumber,
        issuedOn: payslip.createdAt,
        status: cancelled
          ? { label: 'Cancelled', tone: 'danger' }
          : { label: period, tone: 'ok' },
      },
      `Payslip · ${payslip.payslipNumber}`,
      (doc) => {
        drawParties(
          doc,
          { heading: 'Employer', lines: [this.env.DPDP_DATA_FIDUCIARY_NAME, 'India'] },
          {
            heading: 'Employee',
            lines: [employee.fullName, employee.employeeCode, employee.designation ?? ''].filter(
              Boolean,
            ),
          },
        );

        sectionTitle(doc, 'Pay period');
        keyValues(
          doc,
          [
            ['Period', period],
            ['Department', employee.department ?? '—'],
            ['Designation', employee.designation ?? '—'],
            ['Date of joining', formatDate(employee.joinedOn)],
            ['Working days', payslip.workingDays],
            ['Days paid', payslip.payableDays],
            // Only when there was any — a "0.0" line invites the reader to
            // work out whether something is wrong with it.
            ...(Number(payslip.lopDays) > 0
              ? ([['Loss of pay days', payslip.lopDays]] as Array<[string, string]>)
              : []),
            ['Bank', employee.bankName ?? '—'],
            // Last four only. A payslip is forwarded by email far more often
            // than anybody intends, and the full number has no reason to be on it.
            [
              'Account',
              employee.bankAccountNumber
                ? `••••${employee.bankAccountNumber.slice(-4)}`
                : '—',
            ],
            ['PAN', employee.panNumber ?? '—'],
          ],
          { columns: 2, labelWidth: 108 },
        );

        doc.moveDown(0.6);

        sectionTitle(doc, 'Earnings');
        drawTable(
          doc,
          [
            { key: 'label', label: 'Description', weight: 3.4 },
            { key: 'amount', label: 'Amount', weight: 1.1, money: true },
          ],
          payslip.earnings.map((line) => ({ label: line.label, amount: line.amount })),
          { zebra: false },
        );

        if (payslip.deductions.length > 0) {
          sectionTitle(doc, 'Deductions');
          drawTable(
            doc,
            [
              { key: 'label', label: 'Description', weight: 3.4 },
              { key: 'amount', label: 'Amount', weight: 1.1, money: true },
            ],
            payslip.deductions.map((line) => ({ label: line.label, amount: line.amount })),
            { zebra: false },
          );
        }

        const totals: TotalLine[] = [{ label: 'Gross pay', amount: payslip.grossPay }];
        if (Number(payslip.totalDeductions) > 0) {
          totals.push({
            label: 'Total deductions',
            amount: payslip.totalDeductions,
            negative: true,
          });
        }
        totals.push({ label: 'Net pay', amount: payslip.netPay, emphasis: true });

        drawTotals(doc, totals);

        if (payslip.remarks) {
          sectionTitle(doc, 'Remarks');
          doc.font('Helvetica').fontSize(9).fillColor(INK.muted).text(payslip.remarks);
        }

        if (cancelled) {
          drawNotice(
            doc,
            'This payslip has been cancelled and superseded. It is retained for the audit trail and must not be treated as a statement of pay.',
            'danger',
          );
        } else {
          drawNotice(
            doc,
            'Computer-generated payslip. No signature is required. Figures are those recorded for this pay period and are not affected by later salary revisions.',
          );
        }
      },
    );

    return this.publish(
      pdf,
      'invoice',
      payslip.employeeId,
      `${payslip.payslipNumber.replace(/\//g, '-')}.pdf`,
      disposition,
    );
  }

  // ── Shared plumbing ───────────────────────────────────────────────────────

  private async loadRecord(recordId: string) {
    const [row] = await this.db
      .select({
        id: schema.records.id,
        recordCode: schema.records.recordCode,
        status: schema.records.status,
        applicantId: schema.applicants.id,
        applicantName: schema.applicants.fullName,
        applicantCode: schema.applicants.applicantCode,
        recordTitle: schema.achievements.recordTitle,
      })
      .from(schema.records)
      .innerJoin(schema.applicants, eq(schema.applicants.id, schema.records.applicantId))
      .leftJoin(schema.achievements, eq(schema.achievements.recordId, schema.records.id))
      .where(and(eq(schema.records.id, recordId), isNull(schema.records.deletedAt)))
      .limit(1);

    if (!row) throw new NotFoundError('Record');
    return { ...row, recordTitle: row.recordTitle ?? 'Untitled record' };
  }

  /** Write to the vault and hand back a signed URL. */
  private async publish(
    pdf: Buffer,
    scope: 'applicant' | 'record' | 'invoice',
    ownerId: string,
    fileName: string,
    disposition: DocumentDisposition = 'attachment',
  ): Promise<GeneratedDocument> {
    const storageKey = this.storage.buildKey(
      scope === 'invoice' ? 'invoice' : 'attachment',
      ownerId,
      fileName,
    );

    await this.storage.putObject(storageKey, pdf, 'application/pdf');
    const url = await this.storage.presignDownload(storageKey, fileName, disposition);

    return { url, fileName, contentType: 'application/pdf' };
  }
}
