import { Inject, Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { STATUS_META, type RecordStatus } from '@nbr/shared';

import { and, desc, eq, isNull } from 'drizzle-orm';
import { ENV } from '../config/config.module';
import type { Env } from '../config/env';
import { NotFoundError, ValidationError } from '../common/errors';
import type { Database } from '../database/client';
import { DB } from '../database/database.tokens';
import * as schema from '../database/schema';
import { StorageService } from '../storage/storage.service';

/** Dates on a document are read by a person, not parsed — day-month-year. */
function formatDate(value: Date | string | null | undefined): string {
  if (!value) return '—';
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}


export interface GeneratedDocument {
  readonly url: string;
  readonly fileName: string;
}

const PAGE_MARGIN = 48;
const RULE = '#D9DEE8';
const INK = '#10182B';
const INK_2 = '#47536B';
const BRAND = '#0E1B3D';

/**
 * On-demand PDFs: the applicant file, the selection letter and the invoice.
 *
 * Generated per request rather than stored against the record. All three
 * describe the record *as it currently stands*, and a copy written to the vault
 * six weeks ago would show a superseded package price or a former assignee —
 * worse than no copy, because it looks authoritative.
 *
 * The generated bytes are written to storage only so the browser can be handed
 * a short-lived signed URL; the API never streams a file through an app worker
 * (§7). Those objects are disposable — losing one costs a regeneration.
 */
@Injectable()
export class DocumentsService {
  constructor(
    @Inject(DB) private readonly db: Database,
    @Inject(ENV) private readonly env: Env,
    private readonly storage: StorageService,
  ) {}

  // ── Applicant file (§4 Quick Actions, §11.9) ──────────────────────────────

  async applicantFile(applicantId: string): Promise<GeneratedDocument> {
    const [applicant] = await this.db
      .select()
      .from(schema.applicants)
      .where(and(eq(schema.applicants.id, applicantId), isNull(schema.applicants.deletedAt)))
      .limit(1);

    if (!applicant) throw new NotFoundError('Applicant');

    const records = await this.db
      .select({
        recordCode: schema.records.recordCode,
        status: schema.records.status,
        applicationDate: schema.records.applicationDate,
        paymentStatus: schema.records.paymentStatus,
        deliveryStatus: schema.records.deliveryStatus,
        recordTitle: schema.achievements.recordTitle,
      })
      .from(schema.records)
      .leftJoin(schema.achievements, eq(schema.achievements.recordId, schema.records.id))
      .where(and(eq(schema.records.applicantId, applicantId), isNull(schema.records.deletedAt)))
      .orderBy(desc(schema.records.applicationDate));

    const pdf = await this.render((doc) => {
      this.header(doc, 'Applicant file', applicant.applicantCode);

      this.section(doc, 'Applicant');
      this.rows(doc, [
        ['Name', applicant.fullName],
        ['Applicant ID', applicant.applicantCode],
        ['Mobile', applicant.mobile],
        ['Email', applicant.email],
        ['Date of birth', applicant.dateOfBirth ?? '—'],
        [
          'Address',
          [applicant.addressLine, applicant.city, applicant.state, applicant.pincode]
            .filter(Boolean)
            .join(', ') || '—',
        ],
        ['Country', applicant.country ?? '—'],
      ]);

      this.section(doc, `Records (${records.length})`);
      if (records.length === 0) {
        doc.fontSize(9).fillColor(INK_2).text('No records on this profile.');
      } else {
        for (const record of records) {
          const label = STATUS_META[record.status as RecordStatus]?.label ?? record.status;
          doc
            .fontSize(9.5)
            .fillColor(INK)
            .text(`${record.recordCode} — ${record.recordTitle ?? 'Untitled'}`);
          doc
            .fontSize(8.5)
            .fillColor(INK_2)
            .text(
              `${label} · payment ${record.paymentStatus.replace(/_/g, ' ')} · delivery ${record.deliveryStatus.replace(/_/g, ' ')} · applied ${formatDate(record.applicationDate)}`,
            );
          doc.moveDown(0.6);
        }
      }

      // Identity numbers are deliberately absent: they are encrypted, access is
      // logged per read under DPDP §8(4), and a PDF is exactly the artefact that
      // escapes that control by being emailed onward.
      this.note(
        doc,
        'Identity document numbers are omitted. They are held encrypted and released only through an audited reveal.',
      );
    });

    return this.publish(pdf, 'applicant', applicantId, `${applicant.applicantCode}-file.pdf`);
  }

  // ── Selection letter (§11.4) ──────────────────────────────────────────────

  async selectionLetter(recordId: string): Promise<GeneratedDocument> {
    const record = await this.loadRecord(recordId);

    // A letter announcing selection for a record that was not selected would be
    // a document NBR has to stand behind. Refused rather than generated.
    const eligible: readonly string[] = [
      'selected',
      'payment_pending',
      'payment_received',
      'certificate_pending',
      'certificate_uploaded',
      'publication',
      'dispatch_pending',
      'dispatched',
      'delivered',
      'completed',
    ];
    if (!eligible.includes(record.status)) {
      throw new ValidationError({
        status: [
          `This record is at ${STATUS_META[record.status as RecordStatus]?.label ?? record.status}. A selection letter can only be issued once it has been selected.`,
        ],
      });
    }

    const pdf = await this.render((doc) => {
      this.header(doc, 'Letter of selection', record.recordCode);

      doc.moveDown(0.5);
      doc.fontSize(10).fillColor(INK_2).text(formatDate(new Date()));
      doc.moveDown(1);

      doc.fontSize(11).fillColor(INK).text(record.applicantName);
      doc.fontSize(9.5).fillColor(INK_2).text(record.applicantCode);
      doc.moveDown(1);

      doc.fontSize(10.5).fillColor(INK).text('Dear ' + record.applicantName + ',');
      doc.moveDown(0.8);

      doc
        .fontSize(10)
        .fillColor(INK)
        .text(
          `We are pleased to confirm that your achievement, "${record.recordTitle}", has been reviewed by our verification team and selected for entry into the ${this.env.DPDP_DATA_FIDUCIARY_NAME}.`,
          { align: 'justify' },
        );
      doc.moveDown(0.7);
      doc.text(`Your record has been assigned the reference ${record.recordCode}.`, {
        align: 'justify',
      });
      doc.moveDown(0.7);
      doc.text(
        'Please quote this reference in any correspondence. Our team will be in touch with the next steps.',
        { align: 'justify' },
      );

      doc.moveDown(2);
      doc.fontSize(10).fillColor(INK).text('Yours sincerely,');
      doc.moveDown(1.5);
      doc.fontSize(10).text(this.env.DPDP_DATA_FIDUCIARY_NAME);
    });

    return this.publish(pdf, 'record', recordId, `${record.recordCode}-selection-letter.pdf`);
  }

  // ── Invoice (§9, §11.6) ───────────────────────────────────────────────────

  async invoice(recordId: string): Promise<GeneratedDocument> {
    const record = await this.loadRecord(recordId);

    const [payment] = await this.db
      .select()
      .from(schema.payments)
      .where(eq(schema.payments.recordId, recordId))
      .limit(1);

    if (!payment) {
      throw new ValidationError({
        payment: ['No payment has been raised for this record yet.'],
      });
    }

    const [invoice] = await this.db
      .select()
      .from(schema.invoices)
      .where(eq(schema.invoices.paymentId, payment.id))
      .orderBy(desc(schema.invoices.issuedOn))
      .limit(1);

    if (!invoice) {
      throw new ValidationError({
        invoice: ['Generate the invoice number first — the figures are frozen at that point.'],
      });
    }

    const transactions = await this.db
      .select()
      .from(schema.paymentTransactions)
      .where(eq(schema.paymentTransactions.paymentId, payment.id))
      .orderBy(schema.paymentTransactions.paidOn);

    const pdf = await this.render((doc) => {
      this.header(doc, 'Tax invoice', invoice.invoiceNumber);

      this.section(doc, 'Billed to');
      this.rows(doc, [
        ['Name', record.applicantName],
        ['Applicant ID', record.applicantCode],
        ['Record', `${record.recordCode} — ${record.recordTitle}`],
        ['Invoice date', formatDate(invoice.issuedOn)],
        ['Financial year', invoice.financialYear],
      ]);

      // Every figure comes off the invoice row, not the payment plan: the
      // invoice froze them at issue, and a later price change must not
      // retroactively alter a document already sent to an applicant.
      this.section(doc, 'Charges');
      this.rows(doc, [
        [payment.packageName, `INR ${invoice.amount}`],
        // Plain hyphen, not U+2212: pdfkit's built-in fonts use WinAnsi, which
        // has no minus sign, and it renders as a stray quote mark.
        ['Discount', `- INR ${invoice.discount}`],
        [`GST (${payment.gstPercent}%)`, `INR ${invoice.gstAmount}`],
      ]);

      doc.moveDown(0.4);
      doc
        .strokeColor(RULE)
        .lineWidth(0.75)
        .moveTo(PAGE_MARGIN, doc.y)
        .lineTo(doc.page.width - PAGE_MARGIN, doc.y)
        .stroke();
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor(INK).text(`Total payable    INR ${invoice.finalAmount}`);
      doc.fontSize(10).fillColor(INK_2).text(`Received to date    INR ${payment.amountPaid}`);

      if (transactions.length > 0) {
        this.section(doc, 'Payments received');
        for (const transaction of transactions) {
          doc
            .fontSize(9)
            .fillColor(INK_2)
            .text(
              `${formatDate(transaction.paidOn)} · ${transaction.mode.replace(/_/g, ' ')} · INR ${transaction.amount}${transaction.transactionRef ? ` · ref ${transaction.transactionRef}` : ''}${transaction.isReversal ? ' · REVERSAL' : ''}`,
            );
        }
      }

      if (invoice.cancelledAt) {
        doc.moveDown(1);
        doc
          .fontSize(11)
          .fillColor('#C7362F')
          .text(`CANCELLED — ${invoice.cancelReason ?? 'no reason recorded'}`);
      }
    });

    return this.publish(pdf, 'invoice', recordId, `${invoice.invoiceNumber.replace(/\//g, '-')}.pdf`);
  }

  // ── Shared plumbing ───────────────────────────────────────────────────────

  private async loadRecord(recordId: string) {
    const [row] = await this.db
      .select({
        id: schema.records.id,
        recordCode: schema.records.recordCode,
        status: schema.records.status,
        applicantId: schema.applicants.id,
        applicantName: schema.applicants.fullName,
        applicantCode: schema.applicants.applicantCode,
        recordTitle: schema.achievements.recordTitle,
      })
      .from(schema.records)
      .innerJoin(schema.applicants, eq(schema.applicants.id, schema.records.applicantId))
      .leftJoin(schema.achievements, eq(schema.achievements.recordId, schema.records.id))
      .where(and(eq(schema.records.id, recordId), isNull(schema.records.deletedAt)))
      .limit(1);

    if (!row) throw new NotFoundError('Record');
    return { ...row, recordTitle: row.recordTitle ?? 'Untitled record' };
  }

  private render(draw: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      try {
        draw(doc);
      } catch (error: unknown) {
        reject(error instanceof Error ? error : new Error(String(error)));
        return;
      }

      doc.end();
    });
  }

  private header(doc: PDFKit.PDFDocument, title: string, reference: string): void {
    doc.fontSize(15).fillColor(BRAND).text(this.env.DPDP_DATA_FIDUCIARY_NAME);
    doc.fontSize(10.5).fillColor(INK_2).text(title);
    doc.fontSize(9).fillColor(INK_2).text(reference);
    doc.moveDown(0.6);
    doc
      .strokeColor(RULE)
      .lineWidth(1)
      .moveTo(PAGE_MARGIN, doc.y)
      .lineTo(doc.page.width - PAGE_MARGIN, doc.y)
      .stroke();
    doc.moveDown(0.9);
  }

  private section(doc: PDFKit.PDFDocument, title: string): void {
    doc.moveDown(0.8);
    doc.fontSize(8).fillColor(INK_2).text(title.toUpperCase(), { characterSpacing: 0.8 });
    doc.moveDown(0.4);
  }

  private rows(doc: PDFKit.PDFDocument, entries: Array<[string, string]>): void {
    for (const [label, value] of entries) {
      doc.fontSize(9).fillColor(INK_2).text(label, { continued: true });
      doc.fillColor(INK).text(`   ${value}`, { align: 'right' });
    }
  }

  private note(doc: PDFKit.PDFDocument, text: string): void {
    doc.moveDown(1.2);
    doc.fontSize(7.5).fillColor(INK_2).text(text, { align: 'left' });
  }

  /** Write to the vault and hand back a signed URL. */
  private async publish(
    pdf: Buffer,
    scope: 'applicant' | 'record' | 'invoice',
    ownerId: string,
    fileName: string,
  ): Promise<GeneratedDocument> {
    const storageKey = this.storage.buildKey(
      scope === 'invoice' ? 'invoice' : 'attachment',
      ownerId,
      fileName,
    );

    await this.storage.putObject(storageKey, pdf, 'application/pdf');
    const url = await this.storage.presignDownload(storageKey, fileName);

    return { url, fileName };
  }
}
